-- AlterTable
ALTER TABLE `amphoe` MODIFY `deleted_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `province` MODIFY `deleted_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `tambon` MODIFY `deleted_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
